export const SAMPLE_DATA = [
  {
    date: '08/12/2021',
    sourceFrom: 'Online',
    reporterName: 'Selehudin',
    operatorName: 'Afiq B. Shamsul',
    serialNo: 'ABC1234',
    referenceNo: 'Ref123',
    category: 'Category 1',
    status: 'Selesai',
  },
  {
    date: '05/12/2021',
    sourceFrom: 'Online',
    reporterName: 'Amar Haikal',
    operatorName: 'Iman B. Ismail',
    serialNo: 'ABC123456',
    referenceNo: 'Ref1234',
    category: 'Category 2',
    status: 'Selesai',
    key: '2',
  },
  {
    date: '25/11/2021',
    sourceFrom: 'Online',
    reporterName: 'Robert King',
    operatorName: 'Abu. B.Ali',
    serialNo: 'ABC1237',
    referenceNo: 'Ref12345',
    category: 'Category 3',
    status: 'Selesai',
    key: '3',
  },
  {
    date: '30/11/2021',
    sourceFrom: 'Online',
    reporterName: 'Shelawati',
    operatorName: 'Iman B. Ismail',
    serialNo: 'ABC1259',
    referenceNo: 'Ref123456',
    category: 'Category 4',
    status: 'Selesai',
    key: '4',
  },
];
